version: '3.11'

services:
  neo4j:
    image: neo4j:5.20.0
    container_name: neo4j
    ports:
      - "7474:7474"
      - "7687:7687"
    environment:
      NEO4J_AUTH: "neo4j/neo4j_password"
    volumes:
      - neo4j_data:/data

volumes:
  neo4j_data:
