enhancer:
  engine_config:
    engine_type: anthropic
    model_name: claude-3-opus-20240229
    model_params:
      temperature: 0
      max_tokens: 1024
      top_p: 1
summary:
  engine_config:
    engine_type: anthropic
    model_name: claude-3-opus-20240229
    model_params:
      temperature: 0
      max_tokens: 1024
      top_p: 1
keyword_extractor:
  engine_config:
    engine_type: anthropic
    model_name: claude-3-opus-20240229
    model_params:
      temperature: 0
      max_tokens: 1024
      top_p: 1
retriever:
  engine_config:
    engine_type: anthropic
    model_name: claude-3-opus-20240229
    model_params:
      temperature: 0
      max_tokens: 1024
      top_p: 1
reviewer:
  engine_config:
    engine_type: anthropic
    model_name: claude-3-opus-20240229
    model_params:
      temperature: 0
      max_tokens: 1024
      top_p: 1

  

