name: lint

on:
  push:
    branches: [ main, backend ]
  pull_request:

jobs:
  lint:
    strategy:
      matrix:
        python-version: ['3.11']
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependency
        run: pip install flake8 mypy flake8-pyproject
      - name: Run flake8
        run: |
          cd backend
          python -m flake8 resume_assist tests
      - name: Run mypy 
        run: |
          cd backend
          mypy resume_assist